# Generated by Django 4.1.6 on 2023-02-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='heirarchical_cluster',
        ),
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='web.category'),
        ),
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
