# Generated by Django 4.1.6 on 2023-02-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_music_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
