# Generated by Django 4.1.6 on 2023-03-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_event_time_remove_ticket_user_event_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
    ]
