# Generated by Django 4.1.6 on 2023-03-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='web.user'),
            preserve_default=False,
        ),
    ]
