# Generated by Django 4.1.6 on 2023-03-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_ticket_user_remove_ticket_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_musics',
            field=models.ManyToManyField(related_name='liked_users', to='web.music'),
        ),
    ]
